const CONTENT=[
{id:'hinta',title:'Hinta, palinta',cat:'Ölbéli játékok',dur:'2:08',free:true,emoji:'🎵'},
{id:'csip',title:'Csip-csip csóka',cat:'Ujjszámolók',dur:'2:17',free:false,emoji:'🐥'},
{id:'este',title:'Este van már',cat:'Elalvás előtt',dur:'2:31',free:false,emoji:'🌙'},
{id:'utazas',title:'Zötyög a busz',cat:'Utazáshoz',dur:'1:54',free:false,emoji:'🚌'},
{id:'furdes',title:'Csobban a víz',cat:'Fürdéshez',dur:'2:04',free:false,emoji:'🛁'},
{id:'nyugi',title:'3 dal nehéz pillanatokhoz',cat:'Amikor nehéz megnyugodni',dur:'2:42',free:false,emoji:'🤗'},
{id:'mesel',title:'Miért jó az ismétlés?',cat:'Virág mesél',dur:'3:06',free:false,emoji:'🌷'},
{id:'nepdal',title:'Tavaszi szél',cat:'Népdalok',dur:'2:24',free:false,emoji:'🌿'}];
const EVENTS=[
{id:'e1',day:'02',mon:'OKT',title:'Ringató foglalkozás',time:'10:00',place:'Zsolnay Negyed',spots:8,pass:true},
{id:'e2',day:'08',mon:'OKT',title:'Ringató foglalkozás',time:'09:30',place:'Közösségi Ház',spots:3,pass:true},
{id:'e3',day:'17',mon:'OKT',title:'Ringató gyerekkoncert',time:'16:00',place:'Kodály Központ',spots:42,pass:false}];
const DEFAULT={name:'Anna',loggedIn:true,plus:false,favorites:[],queue:[],bookings:[],passRemaining:5,passTotal:8,notifications:true,messages:[{me:false,text:'Szia Anna! Örülök, hogy jöttök csütörtökön. 😊'},{me:true,text:'Szia Virág! A kistesót is vihetjük?'},{me:false,text:'Persze, szeretettel várjuk őt is! 🌷'}],poll:null,checkedIn:false};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem('ringato-v1')||'{}'));let screen='home';let filter='Mind';
function save(){localStorage.setItem('ringato-v1',JSON.stringify(state))}
function nav(){let a=[['home','⌂','Főoldal'],['library','♫','Tár'],['calendar','▣','Programok'],['passes','▦','Jegyeim'],['messages','✉','Üzenet']];document.getElementById('nav').innerHTML=a.map(x=>'<button class="tab '+(screen===x[0]?'active':'')+'" onclick="go(\''+x[0]+'\')"><i>'+x[1]+'</i>'+x[2]+'</button>').join('')}
function go(s){screen=s;render();scrollTo(0,0)}
function render(){nav();let el=document.getElementById('content');el.innerHTML=screen==='home'?home():screen==='library'?library():screen==='calendar'?calendar():screen==='passes'?passes():screen==='messages'?messages():screen==='checkin'?checkin():''}
function home(){let b=state.bookings.length?'<div class="notice success">✓ <b>'+state.bookings.length+' aktív foglalásod van.</b> A részleteket a Programoknál találod.</div>':'';return '<section><div class="welcome"><small>Szia, '+state.name+'! 👋</small><h2>Mit énekeljünk ma?</h2><p>'+(state.plus?'Ringató Plus aktív ✨ · minden tartalom elérhető':'Ingyenes tagság · próbáld ki a Plus tartalmakat')+'</p></div>'+b+'<div class="chips"><button class="chip" onclick="quickFilter(\'Elalvás előtt\')">🌙 Elalváshoz</button><button class="chip" onclick="quickFilter(\'Fürdéshez\')">🛁 Fürdéshez</button><button class="chip" onclick="quickFilter(\'Utazáshoz\')">🚗 Utazáshoz</button><button class="chip" onclick="quickFilter(\'Amikor nehéz megnyugodni\')">🤗 Megnyugváshoz</button></div><div class="sectionTitle"><h3>Neked ajánlom</h3><button class="link" onclick="go(\'library\')">Mind</button></div><div class="cards">'+CONTENT.slice(0,4).map(card).join('')+'</div><div class="sectionTitle"><h3>Következő alkalom</h3><button class="link" onclick="go(\'calendar\')">Naptár</button></div>'+eventRow(EVENTS[0])+'<div class="sectionTitle"><h3>A bérleted</h3><button class="link" onclick="go(\'passes\')">Részletek</button></div>'+passCard()+'<div class="sectionTitle"><h3>Egy gyors kérdés</h3><span class="pill">Virág kérdezi</span></div>'+poll()+'<div class="scope">Interaktív V1 prototípus · a műveletek ezen az eszközön megmaradnak</div></section>'}
function card(c){let locked=!c.free&&!state.plus;return '<div class="card" onclick="openContent(\''+c.id+'\')"><div class="cover">'+c.emoji+'<span class="badge">'+(locked?'PLUS 🔒':c.free?'INGYENES':'PLUS ✓')+'</span><button class="heart" onclick="event.stopPropagation();favorite(\''+c.id+'\')">'+(state.favorites.includes(c.id)?'♥':'♡')+'</button></div><div class="cardtxt"><b>'+c.title+'</b><small>'+c.cat+' · '+c.dur+'</small></div></div>'}
function library(){let cats=['Mind','Ölbéli játékok','Ujjszámolók','Népdalok','Virág mesél','Elalvás előtt'];let list=CONTENT.filter(c=>filter==='Mind'||c.cat===filter);return '<div class="sectionTitle"><h3>Dalok & játékok</h3><button class="link" onclick="showFavorites()">Kedvencek ♥ '+state.favorites.length+'</button></div><input class="field" id="search" placeholder="Keresés…" oninput="searchContent(this.value)"><div class="chips">'+cats.map(c=>'<button class="chip '+(filter===c?'on':'')+'" onclick="setFilter(\''+c+'\')">'+c+'</button>').join('')+'</div><div id="mediaList">'+list.map(mediaRow).join('')+'</div>'}
function mediaRow(c){let locked=!c.free&&!state.plus;return '<div class="listrow" onclick="openContent(\''+c.id+'\')"><div class="round">'+(locked?'🔒':'▶')+'</div><div class="grow"><b>'+c.title+'</b><small>'+c.cat+' · '+c.dur+' · '+(c.free?'INGYENES':'PLUS')+'</small></div><button class="iconBtn" onclick="event.stopPropagation();favorite(\''+c.id+'\')">'+(state.favorites.includes(c.id)?'♥':'♡')+'</button></div>'}
function calendar(){return '<div class="sectionTitle"><h3>Programok</h3><span class="pill">2026 október</span></div><div class="notice">A foglalás itt prototípus-adat. A végleges rendszerben a programokat Virág a WordPress adminban kezeli.</div>'+EVENTS.map(eventRow).join('')+'<div class="sectionTitle"><h3>Foglalásaim</h3></div>'+(state.bookings.length?state.bookings.map(id=>{let e=EVENTS.find(x=>x.id===id);return '<div class="listrow"><div class="round">✓</div><div class="grow"><b>'+e.title+'</b><small>'+e.mon+' '+e.day+'. · '+e.time+' · '+e.place+'</small></div><button class="btn secondary" onclick="cancelBooking(\''+id+'\')">Lemondom</button></div>'}).join(''):'<div class="empty">Még nincs foglalásod.</div>')}
function eventRow(e){let booked=state.bookings.includes(e.id);return '<div class="event"><div class="date">'+e.mon+'<span>'+e.day+'</span></div><div class="grow"><b>'+e.title+'</b><small>'+e.time+' · '+e.place+'<br>'+e.spots+' hely elérhető'+(e.pass?' · bérlettel is':'')+'</small></div>'+(booked?'<span class="pill">✓ Foglalva</span>':'<button class="btn" onclick="book(\''+e.id+'\')">Foglalok</button>')+'</div>'}
function passCard(){let used=state.passTotal-state.passRemaining;return '<div class="pass"><div class="passrow"><div><small>8 ALKALMAS BÉRLET · AKTÍV</small><b style="display:block;font-size:21px">'+state.passRemaining+' alkalom maradt</b><small>Érvényes: 2026. nov. 30-ig</small></div><button class="btn green" onclick="showQR()">QR ▦</button></div><div class="dots">'+Array.from({length:state.passTotal},(_,i)=>'<i class="dot '+(i<used?'used':'')+'"></i>').join('')+'</div></div>'}
function passes(){return '<div class="sectionTitle"><h3>Jegyeim & bérleteim</h3><button class="btn" onclick="shop()">Vásárlás</button></div>'+passCard()+'<div class="sectionTitle"><h3>Közelgő jegyek</h3></div>'+(state.bookings.length?state.bookings.map(id=>{let e=EVENTS.find(x=>x.id===id);return '<div class="listrow"><div class="round">🎟</div><div class="grow"><b>'+e.title+'</b><small>'+e.mon+' '+e.day+'. · '+e.time+'<br>Foglalási azonosító: RV-'+id.toUpperCase()+'26</small></div></div>'}).join(''):'<div class="empty">Nincs közelgő jegyed.</div>')+'<div class="sectionTitle"><h3>Kuponom</h3></div><div class="listrow"><div class="round">🎁</div><div class="grow"><b>BARATNO10</b><small>10% kedvezmény egy családi jegyre</small></div><button class="btn secondary" onclick="toast(\'Kuponkód másolva\')">Másolás</button></div>'}
function messages(){return '<div class="sectionTitle"><h3>Üzenetek Virággal</h3><span class="pill">közvetlen üzenet</span></div><div class="chat">'+state.messages.map(m=>'<div class="bubble '+(m.me?'me':'')+'">'+m.text+'</div>').join('')+'</div><div style="display:flex;gap:8px"><input class="field" style="margin:0" id="msg" placeholder="Írj üzenetet…"><button class="btn" onclick="sendMsg()">➤</button></div><div class="notice">V1-ben ez egyszerű, aszinkron üzenetküldés lenne – nem valós idejű chat.</div>'}
function poll(){if(state.poll)return '<div class="listrow"><div class="round">✓</div><div class="grow"><b>Köszönöm a választ!</b><small>Leggyakrabban: '+state.poll+'</small></div></div>';return '<div class="listrow" style="display:block"><b>Mikor használjátok legszívesebben a dalokat?</b><div class="chips"><button class="chip" onclick="vote(\'utazáskor\')">🚗 Utazás</button><button class="chip" onclick="vote(\'fürdéskor\')">🛁 Fürdés</button><button class="chip" onclick="vote(\'elalváskor\')">🌙 Elalvás</button></div></div>'}
function vote(v){state.poll=v;save();render()}
function setFilter(f){filter=f;render()}function quickFilter(f){filter=f;go('library')}
function searchContent(q){let list=CONTENT.filter(c=>(c.title+' '+c.cat).toLowerCase().includes(q.toLowerCase()));document.getElementById('mediaList').innerHTML=list.map(mediaRow).join('')||'<div class="empty">Nincs találat.</div>'}
function favorite(id){state.favorites.includes(id)?state.favorites=state.favorites.filter(x=>x!==id):state.favorites.push(id);save();render()}
function showFavorites(){let a=CONTENT.filter(c=>state.favorites.includes(c.id));modal('<h2>Kedvenceim ♥</h2>'+(a.length?a.map(mediaRow).join(''):'<div class="empty">Még nincs kedvenced.</div>'))}
function openContent(id){let c=CONTENT.find(x=>x.id===id);if(!c.free&&!state.plus){premium(c);return}player(c)}
function player(c){modal('<div style="text-align:center"><div class="cover" style="height:190px;border-radius:20px">'+c.emoji+'</div><h2 style="margin-top:18px">'+c.title+'</h2><p>'+c.cat+' · '+c.dur+'</p><div class="progress"><i></i></div><div style="font-size:44px;margin:23px">◀︎　⏸　▶︎</div><p><button class="btn secondary" onclick="favorite(\''+c.id+'\');hideModal()">'+(state.favorites.includes(c.id)?'♥ Kedvenc':'♡ Kedvenc')+'</button> <button class="btn secondary" onclick="queue(\''+c.id+'\')">＋ Sorhoz</button></p></div>')}
function queue(id){if(!state.queue.includes(id))state.queue.push(id);save();toast('Hozzáadva a lejátszási sorhoz')}
function premium(c){modal('<h2>Ringató Plus ✨</h2><p><b>'+c.title+'</b> Plus tartalom. Az előfizetéssel a teljes dal- és mondókatár, valamint Virág mini szakmai videói elérhetők.</p><div class="listrow"><div class="grow"><b>Ringató Plus</b><small>Havonta megújuló előfizetés</small></div><b>2 490 Ft/hó</b></div><button class="btn block" onclick="checkout(\'plus\')">Előfizetek</button><p class="tiny">Prototípus: a végleges fizetés Barionon keresztül történne.</p>')}
function checkout(type){if(type==='plus'){modal('<h2>Fizetés</h2><div class="notice">🔒 A végleges alkalmazás innen a Barion biztonságos fizetési felületére irányít.</div><div class="listrow"><div class="grow"><b>Ringató Plus</b><small>Havi előfizetés</small></div><b>2 490 Ft</b></div><button class="btn block" onclick="completePlus()">Demo fizetés sikeresnek jelölése</button>')}}
function completePlus(){state.plus=true;save();modal('<h2>Sikeres előfizetés 🎉</h2><p>Mostantól minden Plus tartalom elérhető.</p><button class="btn block" onclick="hideModal();go(\'library\')">Tartalmak megnyitása</button>')}
function book(id){let e=EVENTS.find(x=>x.id===id);modal('<h2>Helyfoglalás</h2><p><b>'+e.title+'</b><br>'+e.mon+' '+e.day+'. · '+e.time+' · '+e.place+'</p><label>Résztvevők</label><select class="field"><option>1 felnőtt + 1 gyermek</option><option>1 felnőtt + 2 gyermek</option><option>2 felnőtt + 1 gyermek</option></select><div class="notice">'+(e.pass?'Erre az alkalomra a bérleted is használható. Foglaláskor még nem vonunk le alkalmat.':'Ehhez a programhoz külön jegy szükséges.')+'</div><button class="btn block" onclick="confirmBooking(\''+id+'\')">Foglalás megerősítése</button>')}
function confirmBooking(id){if(!state.bookings.includes(id))state.bookings.push(id);save();modal('<h2>Helyed lefoglalva ✓</h2><p>A foglalás bekerült a Programok és a Jegyeim közé.</p><button class="btn block" onclick="hideModal();go(\'passes\')">Jegyeim megnyitása</button>')}
function cancelBooking(id){state.bookings=state.bookings.filter(x=>x!==id);save();render()}
function shop(){modal('<h2>Jegy / bérlet vásárlás</h2><div class="listrow"><div class="grow"><b>Családi jegy</b><small>1 alkalom</small></div><b>2 990 Ft</b></div><div class="listrow"><div class="grow"><b>8 alkalmas bérlet</b><small>Foglalkozásokra</small></div><b>19 990 Ft</b></div><div class="notice">A végleges termékek és rendelések WooCommerce-ben élnek, a fizetés Barionon történik.</div><button class="btn block" onclick="toast(\'Demo: Barion fizetés indulna\')">Tovább a fizetéshez</button>')}
function showQR(){modal('<h2 style="text-align:center">Bérlet bemutatása</h2><div class="qr"></div><p style="text-align:center"><b>'+state.passRemaining+' alkalom maradt</b><br><span class="tiny">RV-DEMO-8PASS-ANNA</span></p><div class="notice">Virág ezt olvassa be a saját mobilos beléptető nézetével.</div><button class="btn secondary block" onclick="hideModal();go(\'checkin\')">Prototípus: Virág beléptető nézete →</button>')}
function checkin(){return '<div class="adminHero"><small>VIRÁG · BELÉPTETÉS</small><h2 style="margin:5px 0">QR ellenőrzés</h2><p style="margin:0;font-size:13px">Ez az egyetlen könnyű kezelőnézet a PWA-ban. A többi adminisztráció WordPress/WooCommerce-ben történik.</p></div><button class="btn green block" onclick="scan()">▦ QR-kód beolvasása</button><div id="scanResult">'+(state.checkedIn?scanResult():'<div class="empty">Olvasd be a vendég bérletét vagy jegyét.</div>')+'</div><button class="btn secondary block" onclick="go(\'home\')">← Vissza a vendég nézethez</button>'}
function scan(){document.getElementById('scanResult').innerHTML='<div class="listrow"><div class="round">👩‍👧</div><div class="grow"><b>Anna · érvényes bérlet</b><small>'+state.passRemaining+' alkalom maradt · lejár: nov. 30.</small></div></div><button class="btn green block" onclick="checkIn()">✓ Beléptetés és 1 alkalom levonása</button>'}
function checkIn(){if(state.passRemaining>0&&!state.checkedIn){state.passRemaining--;state.checkedIn=true;save()}render()}
function scanResult(){return '<div class="notice success">✓ <b>Beléptetve.</b> A bérletből 1 alkalom levonva. Most '+state.passRemaining+' alkalom maradt.</div>'}
function sendMsg(){let i=document.getElementById('msg');if(i&&i.value.trim()){state.messages.push({me:true,text:i.value.trim()});save();render();setTimeout(()=>{state.messages.push({me:false,text:'Köszönöm az üzenetet! Hamarosan válaszolok. 🌷'});save();render()},700)}}
function showNotifications(){modal('<h2>Értesítések 🔔</h2><div class="listrow"><div class="round">🎵</div><div class="grow"><b>Új dal érkezett</b><small>Próbáljátok ki: Zötyög a busz</small></div></div><div class="listrow"><div class="round">📅</div><div class="grow"><b>Holnapi Ringató</b><small>10:00 · Ne felejtsd otthon a jókedvet 😊</small></div></div><p class="tiny">A végleges PWA telepítés után push értesítéseket is kaphat.</p>')}
function showProfile(){modal('<h2>'+state.name+' profilja</h2><p>anna@example.hu</p><div class="listrow"><div>✨</div><div class="grow"><b>Előfizetés</b><small>'+(state.plus?'Ringató Plus aktív':'Ingyenes tagság')+'</small></div></div><div class="listrow"><div>🔔</div><div class="grow"><b>Push értesítések</b><small>Új tartalmak, foglalások</small></div><button class="btn secondary" onclick="toggleNotifications()">'+(state.notifications?'BE':'KI')+'</button></div><button class="btn secondary block" onclick="resetDemo()">Prototípus alaphelyzetbe állítása</button>')}
function toggleNotifications(){state.notifications=!state.notifications;save();showProfile()}
function resetDemo(){localStorage.removeItem('ringato-v1');state=JSON.parse(JSON.stringify(DEFAULT));hideModal();go('home')}
function modal(h){document.getElementById('sheet').innerHTML=h;document.getElementById('modal').classList.add('on')}function hideModal(){document.getElementById('modal').classList.remove('on')}function toast(t){modal('<h2>'+t+'</h2><button class="btn block" onclick="hideModal()">Rendben</button>')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();